import type { MotionRailOptions } from "./types";
export declare class MotionRail {
  readonly element: HTMLElement;
  readonly scrollable: HTMLElement;
  private rtl;
  private autoplay;
  private delay;
  private resumeDelay;
  private onChange?;
  private handleStateChange;
  private extensions;
  private breakpoints;
  private autoPlayIntervalId;
  private autoPlayTimeoutId;
  private isDragging;
  private startX;
  private startLogicalScroll;
  private cancelScroll;
  private lastPointerX;
  private lastPointerTime;
  private velocity;
  private pointerId;
  private snapPoints;
  private resizeObserver;
  private intersectionObserver;
  private state;
  constructor(element: HTMLElement, options: MotionRailOptions);
  private randomContainerName;
  private setBreakPoints;
  private getLogicalScroll;
  private setLogicalScroll;
  private scrollToLogical;
  private observeResize;
  private observeEdgeItems;
  private cacheSnapPoints;
  private findNearestSnapPoint;
  private attachPointerEvents;
  private handlePointerDown;
  private handlePointerMove;
  private handlePointerUp;
  private animateLogicalScroll;
  private scrollByPage;
  play(): void;
  next(): void;
  prev(): void;
  pause(): void;
  scrollToIndex(index: number): void;
  getState(): {
    visibleItemIndexes: number[];
    totalItems: number;
    isFirstItemVisible: boolean;
    isLastItemVisible: boolean;
  };
  getOptions(): {
    autoplay: boolean;
    rtl: boolean;
    delay: number;
    resumeDelay: number;
    breakpoints: {
      width?: number;
      columns?: number;
      gap?: string;
    }[];
  };
  update(): void;
  destroy(): void;
}
